language: go
sudo: false
go:
  - 1.10.x
  - master

before_script:
  - go vet ./...
  - FMT=`go fmt ./...` && [ -z "$FMT" ]

script:
  - go test -coverprofile=coverage.txt -covermode=atomic
  - go test -race

after_success:
  - bash <(curl -s https://codecov.io/bash)
