#!/bin/sh
set -e
export GOPATH=/tmp:/usr/share/gocode
export GOFLAGS=-mod=vendor

rm -rf /tmp/src/github.com/ubuntu/
mkdir -p /tmp/src/github.com/ubuntu/
cp -a . /tmp/src/github.com/ubuntu/ubuntu-report

